import {
  calculateIntelligenceScore,
} from './intelligence.scoring.js'

import {
  getTravellerPreferences,
  getDestinationForIntelligence,
  getDestinationIntelligence,
  getDestinationExperiences,
} from './intelligence.service.js'

import type {
  IntelligenceResult,
} from './intelligence.types.js'

import type {
  Recommendation,
  RecommendationFilters,
  RecommendationResponse,
} from './recommendation.types.js'

import { supabaseAdmin } from '../config/supabase.js'

/**
 * Convert the overall intelligence score into
 * a human-readable match label.
 */
function getMatchLabel(
  score: number,
): Recommendation['match_label'] {
  if (score >= 90) return 'Exceptional match'
  if (score >= 80) return 'Excellent match'
  if (score >= 70) return 'Strong match'
  if (score >= 55) return 'Good match'
  if (score >= 40) return 'Fair match'

  return 'Low match'
}

/**
 * Convert the confidence level generated by
 * Khoj Intelligence into a recommendation label.
 */
function getConfidenceLabel(
  confidence: IntelligenceResult['score']['confidence'],
): Recommendation['confidence_label'] {
  switch (confidence.level) {
    case 'high':
      return 'High confidence'

    case 'moderate':
      return 'Moderate confidence'

    case 'limited':
    default:
      return 'Limited confidence'
  }
}

/**
 * Fetch all destinations that can participate
 * in Smart Discovery.
 *
 * We intentionally keep this query simple and only
 * use columns that already exist in the destinations table.
 */
async function getActiveDestinations() {
  const { data, error } = await supabaseAdmin
    .from('destinations')
    .select(`
      id,
      name,
      slug,
      short_description,
      destination_type,
      featured,
      verified
    `)
    .order('featured', { ascending: false })
    .order('name', { ascending: true })

  if (error) {
    throw new Error(
      `Failed to fetch destinations: ${error.message}`,
    )
  }

  return data ?? []
}

/**
 * Check whether a destination passes the optional
 * Smart Discovery filters.
 */
function passesFilters(
  destination: {
    destination_type: string | null
  },
  profile: {
    state_name: string | null
  },
  filters?: RecommendationFilters,
): boolean {
  if (!filters) {
    return true
  }

  if (
    filters.destination_type &&
    destination.destination_type?.toLowerCase() !==
      filters.destination_type.toLowerCase()
  ) {
    return false
  }

  if (
    filters.preferred_region &&
    profile.state_name?.toLowerCase() !==
      filters.preferred_region.toLowerCase()
  ) {
    return false
  }

  return true
}

/**
 * Build Smart Discovery recommendations for a traveller.
 *
 * Important:
 * This function does NOT create another scoring system.
 * Every destination is evaluated using the existing
 * Khoj Intelligence scoring engine.
 */
export async function getSmartRecommendations(
  userId: string,
  filters?: RecommendationFilters,
): Promise<RecommendationResponse> {
  /**
   * 1. Get traveller preferences once.
   */
  const traveller = await getTravellerPreferences(userId)

  /**
   * 2. Get the available destination inventory.
   */
  const destinations = await getActiveDestinations()

  if (destinations.length === 0) {
    return {
      recommendations: [],
      summary: {
        total_destinations_evaluated: 0,
        recommendations_returned: 0,
        top_match: null,
      },
    }
  }

  /**
   * 3. Evaluate every destination.
   *
   * Promise.all allows independent destination
   * intelligence queries to run concurrently.
   */
  const evaluatedRecommendations = await Promise.all(
    destinations.map(async (destination) => {
      /**
       * Fetch the complete intelligence profile
       * required by the existing scoring engine.
       */
      const [
        destinationProfile,
        intelligence,
        experiences,
      ] = await Promise.all([
        getDestinationForIntelligence(destination.id),
        getDestinationIntelligence(destination.id),
        getDestinationExperiences(destination.id),
      ])

      /**
       * Apply optional filters after obtaining the
       * intelligence-compatible destination profile.
       */
      if (
        !passesFilters(
          destination,
          destinationProfile,
          filters,
        )
      ) {
        return null
      }

      /**
       * IMPORTANT:
       * Smart Discovery uses the exact same intelligence
       * engine that powers the destination intelligence page.
       */
      const intelligenceResult =
        calculateIntelligenceScore({
          traveller,
          destination: destinationProfile,
          intelligence,
          experiences,
        })

      const recommendation: Recommendation = {
        rank: 0,

        destination: {
          id: destination.id,
          name: destination.name,
          slug: destination.slug,
          short_description:
            destination.short_description,
          destination_type:
            destination.destination_type,
          featured: destination.featured,
          verified: destination.verified,
        },

        intelligence: intelligenceResult,

        match_label: getMatchLabel(
          intelligenceResult.score.overall,
        ),

        confidence_label: getConfidenceLabel(
          intelligenceResult.score.confidence,
        ),
      }

      return recommendation
    }),
  )

  /**
   * Remove destinations rejected by filters.
   */
  const recommendations = evaluatedRecommendations.filter(
    (
      recommendation,
    ): recommendation is Recommendation =>
      recommendation !== null,
  )

  /**
   * 4. Rank recommendations.
   *
   * Primary:
   *   overall intelligence score
   *
   * Secondary:
   *   personal fit
   *
   * Tertiary:
   *   impact score
   *
   * This means the recommendation engine does not
   * randomly choose between similar destinations.
   */
  recommendations.sort((a, b) => {
    const overallDifference =
      b.intelligence.score.overall -
      a.intelligence.score.overall

    if (overallDifference !== 0) {
      return overallDifference
    }

    const personalFitDifference =
      b.intelligence.score.personal_fit -
      a.intelligence.score.personal_fit

    if (personalFitDifference !== 0) {
      return personalFitDifference
    }

    const impactA =
      a.intelligence.score.impact ?? -1

    const impactB =
      b.intelligence.score.impact ?? -1

    return impactB - impactA
  })

  /**
   * 5. Apply max_results AFTER ranking.
   */
  const maxResults =
    filters?.max_results && filters.max_results > 0
      ? Math.floor(filters.max_results)
      : recommendations.length

  const limitedRecommendations =
    recommendations.slice(0, maxResults)

  /**
   * 6. Assign final ranks.
   */
  limitedRecommendations.forEach(
    (recommendation, index) => {
      recommendation.rank = index + 1
    },
  )

  /**
   * 7. Build summary.
   */
  const topRecommendation =
    limitedRecommendations[0] ?? null

  return {
    recommendations: limitedRecommendations,

    summary: {
      total_destinations_evaluated:
        destinations.length,

      recommendations_returned:
        limitedRecommendations.length,

      top_match: topRecommendation
        ? {
            destination_id:
              topRecommendation.destination.id,

            destination_name:
              topRecommendation.destination.name,

            score:
              topRecommendation.intelligence.score
                .overall,
          }
        : null,
    },
  }
}